### PR TITLE
Replace Opinion with Soccer newsletter for US

### PR DESCRIPTION
**Pull request by vlbee**
## What does this change?

Removes Opinion newsletter and replaces with Soccer newsletter for US newsletter onboarding flow. 

Please not the soccur newsletter with ID 6030 does not exist in CODE if testing in code, so will not render on the page. 

Code newsletters are not being updated, so I will raise a separate PR to use PROD idapi endpoint for reading all newsletter information, when otherwise pointing to CODE. This means some newsletter updates in CODE gateway might not actually persist because in the rest of CODE that newsletter ID does not yet exist. 

## Images

Soccer newsletter title/description not uploaded to CODE environment, hence the weird text as I've used a random test id just to get it to render for the image. 
US image title was very wide, so could not get it to fit so had to add some css override code to add background filler top and bottom. 

image

image

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Review by lindseydew — COMMENTED** [review]
Code looks good to me. Would be keen to run this locally to see it in action, but had a little trouble on my machine, so perhaps we could go through it?

**Comment by vlbee** [comment]
I'm addding a newsletter localization readme in this draft pr the Europe localisation

**Review by lindseydew — DISMISSED** [review]
LGTM 👍

**Review by lindseydew — APPROVED** [review]
Nice work

**Pull request merged**
