### PR TITLE
Don't hide success

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What does this change?
Shows the success message for longer

Previously, we removed the success message from the page after n seconds. Now we keep it on there all the time, only hiding it when Resend Email is clicked

### Before
b

### After
a

### CODE REVIEW

**Comment by oliverlloyd** [comment]
[Show/Hide Success based on `loading`](https://trello.com/c/aCUbzmUm/3322-show-hide-success-based-on-loading)

**Review by ob6160 — APPROVED** [review]
lgtm :)

**Comment by ob6160** [comment]
> lgtm :)

One quick question. If the resend fails for some reason do we want to display an error message instead of never setting loading state back to false?

**Comment by oliverlloyd** [comment]
> > lgtm :)
> 
> One quick question. If the resend fails for some reason do we want to display an error message instead of never setting loading state back to false?

In this case the form submission causes the page to reload so there's no need to change state. Indeed, it's not even possible because there's no callback or onResponse event. I agree though it's a bit confusing having the state seemingly just hang, but because we're using forms for making POST requests instead of, say, using `fetch`, this is how it works

If there's an error on the server then we render the page that the form was POSTing to (`previousPage`) with an error message.

**Pull request merged**
