### PR TITLE
14th June 2021 | Updating dependencies

### PR DESCRIPTION
**Pull request by coldlink**
## What does this change?
- Updates dependencies to the latest versions and clean up most of the dependency update PRs from dependabot

## Notes
- `@types/node` wasn't updated as this caused a clash with `express` types, so we can investigate that separately.
- `typescript` wasn't updated as this causes an issue with `chromatic`
- `@babel/preset-react` wasn't updates as this causes an issue with visual regression in storybook

## Tested?
- [x] Local
- [x] CI
- [ ] CODE

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
Yup

**Comment by oliverlloyd** [comment]
> Yup

That said, these visual diffs are wild

**Comment by coldlink** [comment]
Yeah, not sure whats up with the visual diffs. I'll investigate.

**Comment by coldlink** [comment]
very weird, caused by an update to `@babel/preset-react`, but it's only affecting storybook and not the main application 🤔

**Comment by oliverlloyd** [comment]
> very weird, caused by an update to `@babel/preset-react`, but it's only affecting storybook and not the main application 🤔

Shall we hold off on that update for a while? Maybe if the code Gods are smiling on us by the time we revisit it there might be an update to SB which fixes it. If not, we can invest some time to investigate more

**Comment by coldlink** [comment]
Yeah, I'll add it to the notes, and merge as is.

**Pull request merged**
